services:
  - type: web
    name: biasclean-api
    env: python
    pythonVersion: "3.10.13"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 biasclean_app:app
