services:
  - type: web
    name: biasclean-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python baisclean.py  # Changed from app.py to baisclean.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0